version: '3.9'
services:
  database:
    image: postgres:alpine
    container_name: postgresDB
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: honackDB
volumes:
  db_data:
